apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chroma
  namespace: workmate
spec:
  serviceName: "chroma-service"
  replicas: 1
  selector:
    matchLabels:
      app: chroma
  template:
    metadata:
      labels:
        app: chroma
    spec:
      containers:
        - name: chroma
          image: chromadb/chroma:latest
          ports:
            - containerPort: 8000
          env:
            - name: IS_PERSISTENT
              value: "TRUE"
            - name: PERSIST_DIRECTORY
              value: "/chroma/chroma"
          volumeMounts:
            - name: chroma-data
              mountPath: "/chroma/chroma"
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: chroma-data
          hostPath:
            path: "/data/chroma"
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: chroma-service
  namespace: workmate
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: chroma
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
